apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
      - name: cluster-autoscaler
        image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.34.0
        command:
        - ./cluster-autoscaler
        - --cloud-provider=aws
        - --cluster-name=fastapi-eks-cluster
        - --balance-similar-node-groups
        - --skip-nodes-with-system-pods=false
        - --skip-nodes-with-local-storage=false
        - --stderrthreshold=info
        - --v=4
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
